name: Intip Secrets

on:
  workflow_dispatch: # Memperbolehkan kita menjalankan workflow ini secara manual

jobs:
  reveal-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Membaca Secret
        run: |
          # Kita gunakan trik memecah teks atau encode ke Base64 agar tidak disensor GitHub
          echo "Memproses secret..."
        
          echo "DOCKER_HUB_ACCESS_TOKEN dalam bentuk HEX:"
          echo -n "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | xxd -p
